name: build-default

on:
  push:
    branches: [ "server_with_websocket" ]
  pull_request:
    branches: [ "server_with_websocket" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore 'MqttApiPg.sln'
    - name: Build
      run: dotnet build 'MqttApiPg.sln' --no-restore
    - name: Test
      run: dotnet test 'MqttApiPg.sln' --no-build --verbosity normal
