name: Heroku Deploy

on:
  push:
    branches: [ "server_with_websocket" ]
  pull_request:
    branches: [ "server_with_websocket" ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: AkhileshNS/heroku-deploy@v3.12.12
            with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_email: "brendonbenevides@gmail.com"
                heroku_app_name: "dotnet-deploy-test"
                branch: "server_with_websocket"
                usedocker: "true"
            env:
                HD_ASPNETCORE_ENVIRONMENT: "Development"